import type { Metadata } from "next";
<<<<<<< HEAD
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
=======
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
>>>>>>> 1de0301 (Setting up authentication with Clerk)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
=======
    <ClerkProvider>
      <html lang="en" data-theme="light">
        <body>{children}</body>
      </html>{" "}
    </ClerkProvider>
>>>>>>> 1de0301 (Setting up authentication with Clerk)
  );
}
